### ISSUE TITLE
Next build error: Cannot read property 'modalNode' of null

### ISSUE THREAD

**Issue by Clement-Bresson** [AlexanderRichey/styled-react-modal#16]
There seems to be an error when trying to build a project using `styled-react-modal` with next for production.

Below is production script output.

```
TypeError: Cannot read property 'modalNode' of null
    at Object.children (/home/cbresson/DEV/TACOTAX/tacofront/node_modules/styled-react-modal/build/index.js:1:7634)
    at a.render (/home/cbresson/DEV/TACOTAX/tacofront/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:64)
    at a.read (/home/cbresson/DEV/TACOTAX/tacofront/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:58)
    at renderToString (/home/cbresson/DEV/TACOTAX/tacofront/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:53:83)
    at render (/home/cbresson/DEV/TACOTAX/tacofront/node_modules/next-server/dist/server/render.js:42:16)
    at renderPage (/home/cbresson/DEV/TACOTAX/tacofront/node_modules/next-server/dist/server/render.js:102:16)
    at t.renderPage (/home/cbresson/DEV/TACOTAX/tacofront/.next-production/server/static/unique-build/pages/_document.js:1:7885)
    at Function.value (/home/cbresson/DEV/TACOTAX/tacofront/.next-production/server/static/unique-build/pages/_document.js:1:16429)
    at /home/cbresson/DEV/TACOTAX/tacofront/.next-production/server/static/unique-build/pages/_document.js:1:7995
    at tryCatch (/home/cbresson/DEV/TACOTAX/tacofront/node_modules/regenerator-runtime/runtime.js:62:40)

```

**Comment by AlexanderRichey** [comment]
Fixed in #17. Thanks @Clement-Bresson!
